apiVersion: apps/v1
kind: Deployment
metadata:
  name: even-odd-app
  labels:
    app: even-odd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: even-odd-app
  template:
    metadata:
      labels:
        app: even-odd-app
    spec:
      containers:
      - name: even-odd-app
        image: 23mis0471/even-odd-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: even-odd-service
spec:
  selector:
    app: even-odd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
